#!/bin/bash

# deskSpy 

# continuous desktop spy, to be used in tint2 
# executor scripts with 'execp_continuous = 1'

#non="_"
#act="-"

non="◌"
act="◍"

non="0"
act="1"

non="_"
act="-"

non="◌"
act="◍"

act="■"
non="□"

# ^https://www.w3schools.com/charsets/ref_utf_geometric.asp

count=0 # for debugging only

(xprop -root -spy _NET_CURRENT_DESKTOP _NET_NUMBER_OF_DESKTOPS)  | 
while read
do

    ((count+=1))

    read -r _ _ desk <<< $(xprop -root _NET_CURRENT_DESKTOP) && ((desk+=1))
    read -r _ _ num <<< $(xprop -root _NET_NUMBER_OF_DESKTOPS)
        
    # some real code here
    sum=""
    for n in $(seq "$num"); do
    
        if [ "$n" == "$desk" ]; then
            sum="$sum [ $desk ]"
        else
            sum="$sum $n"
        fi
    done

    echo "$sum"    
    #>&2 echo "($count) desktop $desk / $num" # for debugging only
    #echo "[$desk] / $num"
done
